version: '3.8'

services:
  calculator_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: calculator_app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development